In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
from sklearn.model_selection import train_test_split

from rbm import RBM
from MC_Ising2D import IsingMC

import torch
import torch.nn as nn
torch.manual_seed(12)

L = 10

In [3]:
rbm = RBM()
rbm = torch.load('RBM_trained_models/RBM_model_T_complete_nv100_nh100_lr1.0E-02_k1_bsize100_nepochs8000.pt',
                 map_location= 'cpu')

/home/rodrigo/anaconda3/lib/python3.6/site-packages/torch/serialization.py:425: SourceChangeWarning: source code of class 'rbm.RBM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)


In [21]:
rbm = RBM()
rbm = torch.load('RBM_trained_models/RBM_model_T_zero_inf_nv10000_nh10000_lr1.0E-03_k1_bsize100_nepochs1000.pt',
                 map_location= 'cpu')

In [22]:
W, vb, hb = rbm.parameters()

In [23]:
W

tensor([[-0.1111,  0.0643,  0.2242,  ..., -0.0524,  0.0321, -0.1046],
        [-0.0394, -0.0640, -0.0288,  ...,  0.1811, -0.0071, -0.0813],
        [-0.0256,  0.0878, -0.0194,  ..., -0.1593,  0.1736, -0.0743],
        ...,
        [ 0.0191,  0.0396,  0.1016,  ..., -0.0275, -0.0389, -0.0415],
        [ 0.0560,  0.0453,  0.2024,  ...,  0.0897,  0.0512, -0.1385],
        [-0.0061, -0.1494,  0.0128,  ...,  0.2705, -0.0838,  0.1274]])

In [24]:
W.shape

torch.Size([10000, 10000])

In [25]:
W

tensor([[-0.1111,  0.0643,  0.2242,  ..., -0.0524,  0.0321, -0.1046],
        [-0.0394, -0.0640, -0.0288,  ...,  0.1811, -0.0071, -0.0813],
        [-0.0256,  0.0878, -0.0194,  ..., -0.1593,  0.1736, -0.0743],
        ...,
        [ 0.0191,  0.0396,  0.1016,  ..., -0.0275, -0.0389, -0.0415],
        [ 0.0560,  0.0453,  0.2024,  ...,  0.0897,  0.0512, -0.1385],
        [-0.0061, -0.1494,  0.0128,  ...,  0.2705, -0.0838,  0.1274]])

In [35]:
torch.potrf(W_)

RuntimeError: Lapack Error in potrf : the leading minor of order 1 is not positive definite at /opt/conda/conda-bld/pytorch_1533672544752/work/aten/src/TH/generic/THTensorLapack.cpp:626

In [12]:
W[3,4].item()

0.13943813741207123

In [14]:
W.shape[0]

100

In [28]:
for j in range(W.shape[0]):
    for k in range(W.shape[0]):
        if j != k:
            
            if W[j,k].item() != W[j,k].item():
                print(j)
                print(k)
                break

In [31]:
import numpy as np

def is_pos_def(x):
    return np.all(np.linalg.eigvals(x) >= 0)

In [32]:
W.numpy()

array([[-0.11110839,  0.06434952,  0.2242005 , ..., -0.05236919,
         0.03210198, -0.10458258],
       [-0.03943063, -0.06395333, -0.02875776, ...,  0.18106578,
        -0.00712755, -0.0813032 ],
       [-0.025645  ,  0.08782783, -0.01941821, ..., -0.15932715,
         0.1735835 , -0.07432071],
       ...,
       [ 0.01913099,  0.03962976,  0.10158475, ..., -0.02745914,
        -0.03891495, -0.04150459],
       [ 0.05596967,  0.04529618,  0.20240082, ...,  0.08966662,
         0.0512402 , -0.13853505],
       [-0.00605863, -0.14944518,  0.0128254 , ...,  0.2705383 ,
        -0.08378427,  0.12739433]], dtype=float32)

In [33]:
is_pos_def(W.numpy())

False

In [34]:
W_ = (W + W.t())/2

In [9]:
a = torch.randn(3, 3)
a = torch.mm(a, a.t()) # make symmetric positive-definite
l = torch.potrf(a)
l

tensor([[ 0.5038, -0.5591, -0.8822],
        [ 0.0000,  1.3979,  0.3537],
        [ 0.0000,  0.0000,  2.3173]])

In [10]:
print(torch.__version__)

0.4.1
